PyTorch. Вступ

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.6.0+cpu


*Tensors*

Число

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

Вектор

In [6]:
vector = torch.tensor([1,2,3,4,5])
vector.ndim

1

Матриця

In [7]:
matrix = torch.tensor([[1,2,3],[4,5,6]])
matrix.ndim

2

In [8]:
matrix.shape

torch.Size([2, 3])

Створення tensor

In [9]:
TENSOR = torch.tensor([[1,2,3],
                       [4,5,6],
                       [7,8,9]])
TENSOR.shape

torch.Size([3, 3])

In [10]:
random_tensor = torch.rand(2, 3, 4)
random_tensor

tensor([[[0.1022, 0.6518, 0.8767, 0.4948],
         [0.7779, 0.8465, 0.4293, 0.3846],
         [0.1732, 0.5184, 0.8191, 0.7051]],

        [[0.2396, 0.4908, 0.5187, 0.1928],
         [0.5853, 0.3623, 0.1929, 0.6867],
         [0.4259, 0.3011, 0.8946, 0.6983]]])

tensor, який є схожим до тезора картинки

In [11]:
random_image_size_tensor = torch.rand(size=(3,224,224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

Бінарні тензори

In [12]:
zero = torch.zeros(3, 4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [13]:
ones = torch.ones(3, 4)
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

Тензор множини

In [14]:
range = torch.arange(start=0, end=1000, step=5)
range

tensor([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
         70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125, 130, 135,
        140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190, 195, 200, 205,
        210, 215, 220, 225, 230, 235, 240, 245, 250, 255, 260, 265, 270, 275,
        280, 285, 290, 295, 300, 305, 310, 315, 320, 325, 330, 335, 340, 345,
        350, 355, 360, 365, 370, 375, 380, 385, 390, 395, 400, 405, 410, 415,
        420, 425, 430, 435, 440, 445, 450, 455, 460, 465, 470, 475, 480, 485,
        490, 495, 500, 505, 510, 515, 520, 525, 530, 535, 540, 545, 550, 555,
        560, 565, 570, 575, 580, 585, 590, 595, 600, 605, 610, 615, 620, 625,
        630, 635, 640, 645, 650, 655, 660, 665, 670, 675, 680, 685, 690, 695,
        700, 705, 710, 715, 720, 725, 730, 735, 740, 745, 750, 755, 760, 765,
        770, 775, 780, 785, 790, 795, 800, 805, 810, 815, 820, 825, 830, 835,
        840, 845, 850, 855, 860, 865, 870, 875, 880, 885, 890, 8

Створення нульового тензора копіюванням розміру

In [15]:
zero_range = torch.zeros_like(input=range)
zero_range

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0])

Типи даних тензорів (datatypes)

3 ймовірні помилки в PyTorch

1.) Тип даних

2.) Розмірність

3.) Невірний девайс

In [16]:
float16_tensor = torch.tensor([3,6,9], dtype=torch.float16, # тип даних тензору
                            device=None, # На якому девайсі тензор
                            requires_grad=False)
float16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [17]:
float32_tensor = float16_tensor.type(torch.float32)
float32_tensor

tensor([3., 6., 9.])

In [18]:
float16_tensor * float32_tensor

tensor([ 9., 36., 81.])

Отримання параметрів тензору

In [19]:
some_tensor = torch.randn(3, 4)
some_tensor

tensor([[ 0.3793,  0.1780,  0.1634, -0.0015],
        [ 0.2400, -1.1011, -0.6730, -0.7773],
        [ 0.5644,  0.6363, -0.0665, -0.3495]])

In [20]:
print(f"Datatype:{some_tensor.dtype}\n"
      f"Shape:{some_tensor.shape}\n"
      f"Device:{some_tensor.device}")

Datatype:torch.float32
Shape:torch.Size([3, 4])
Device:cpu


Маніпуляції з тензорами:
* '+'
* '-'
* '*'
* '/'
* '* [ ]'

In [21]:
tensor = torch.tensor([1, 2, 3, 4, 5])
# torch.add(tensor, 10)
tensor + 10

tensor([11, 12, 13, 14, 15])

In [22]:
tensor - 10

tensor([-9, -8, -7, -6, -5])

In [23]:
# torch.mul(tensor, 10)
tensor * 10

tensor([10, 20, 30, 40, 50])

In [24]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000])

Матричне множення

(ВИМОГА: КІЛЬКІСТЬ СТОВПЦІВ ПЕРШОЇ МАТРИЦІ ДОРІВНЮЄ КІЛЬКОСТІ РЯДКІВ ДРУГОЇ МАТРИЦІ)

* (a, b) @ (b, c) -> (a, c)

In [25]:
# torch.matmul(tensor, tensor)
# torch.mm(tensor, tensor)
tensor @ tensor

tensor(55)

Транспонування матриці

In [26]:
print(torch.tensor([[1,2,3],
                    [4,5,6]]).T)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


min, max, mean, sum

In [27]:
x = torch.arange(start=1, end=10, step=5)
x

tensor([1, 6])

min, max

In [28]:
torch.min(x), torch.max(x)

(tensor(1), tensor(6))

In [29]:
x.max(), x.min()

(tensor(6), tensor(1))

Медіана

In [30]:
torch.mean(x.type(torch.float32))

tensor(3.5000)

In [31]:
x.type(torch.float32).mean()

tensor(3.5000)

Сума

In [32]:
x.sum(), torch.sum(x)

(tensor(7), tensor(7))

Позиція min та max

In [33]:
x.argmin()

tensor(0)

In [34]:
x.argmax()

tensor(1)

torch.squeeze - прибирання розмірності, в яких один елемент

Приклад: 3D -> 2D, якщо тільки один шар по z

In [37]:
torch.tensor([[1,2,3]]).shape

torch.Size([1, 3])

In [38]:
torch.tensor([[1,2,3]]).squeeze().shape

torch.Size([3])

unsqueeze(dim=0) - Додавання розмірності в позиції, яка вказана у параметрі dim

Приклад: 2D -> 3D, якщо dim = 0

In [43]:
torch.tensor([[1,2,3]]).unsqueeze(dim=0).shape

torch.Size([1, 1, 3])

permute -> Переміщення розмірностей. Зміна shape

In [45]:
x_original = torch.rand(size=(224,224,3))
x_original.shape

torch.Size([224, 224, 3])

In [46]:
x_permuted = x_original.permute(0,2,1)
x_permuted.shape

torch.Size([224, 3, 224])

Індексація

reshape - перебудова шейпу тензора. У випадку нижче - з масиву створюється шар кубу (3D)

In [50]:
x = torch.arange(start=1, end=10, step=1).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [51]:
x[0][1][0]

tensor(4)

In [52]:
x[:]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

З першої розмірності отримати елемент по першому індексу

In [55]:
print(x[:, 1])

tensor([[4, 5, 6]])


З першої розмірності, в усіх її елементах, узяти елементи за першим індексом

In [56]:
print(x[:, :, 1])

tensor([[2, 5, 8]])


## PyTorch та tensors на GPU